### ISSUE TITLE
Create the cq:dialog.xml

### ISSUE THREAD

**Issue by br027096** [Citytechinc/cq-component-maven-plugin#17]
Would be nice since it seems like Adobe is moving towards the Touch UI interface to start creating and deploying the cq:dialog.xml as part of the dialog.xml creation process.  Thanks!

**Comment by pmichelotti** [comment]
Release 4.0.0 now supports Touch UI as well - see http://code.citytechinc.com/cq-component-maven-plugin/index.html and http://www.citytechinc.com/us/en/blog/2015/09/introducing-touchui.html for more details
